//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurirobotSupporter.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NurirobotSupporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   장비를 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Alert_No_BaudRate {
            get {
                return ResourceManager.GetString("Alert_No_BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시리얼포트에 이미 연결되어 있습니다. 연결을 해제하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Alert_Serial_Connected {
            get {
                return ResourceManager.GetString("Alert_Serial_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_DeviceSearch {
            get {
                return ResourceManager.GetString("Button_DeviceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결해제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Disconnect {
            get {
                return ResourceManager.GetString("Button_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_English {
            get {
                return ResourceManager.GetString("Button_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한국어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Korean {
            get {
                return ResourceManager.GetString("Button_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Search_Start {
            get {
                return ResourceManager.GetString("Button_Search_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Search_Stop {
            get {
                return ResourceManager.GetString("Button_Search_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 연결 정보을 찾습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lable_DeviceSearchDesc {
            get {
                return ResourceManager.GetString("Lable_DeviceSearchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lable_PopupTitleDeviceSearch {
            get {
                return ResourceManager.GetString("Lable_PopupTitleDeviceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   끄기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lable_StartupPopupOff {
            get {
                return ResourceManager.GetString("Lable_StartupPopupOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   켜기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lable_StartupPopupOn {
            get {
                return ResourceManager.GetString("Lable_StartupPopupOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Left_Menu_English {
            get {
                return ResourceManager.GetString("Left_Menu_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Left_Menu_Help {
            get {
                return ResourceManager.GetString("Left_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Left_Menu_Language {
            get {
                return ResourceManager.GetString("Left_Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매크로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Left_Menu_Macro {
            get {
                return ResourceManager.GetString("Left_Menu_Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다중 제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Left_Menu_Multiple_Control {
            get {
                return ResourceManager.GetString("Left_Menu_Multiple_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Left_Menu_Search {
            get {
                return ResourceManager.GetString("Left_Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Left_Menu_Setting {
            get {
                return ResourceManager.GetString("Left_Menu_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   단독 제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Left_Menu_Single_Control {
            get {
                return ResourceManager.GetString("Left_Menu_Single_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메뉴과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Left_Menu_Title {
            get {
                return ResourceManager.GetString("Left_Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   처리중입니다. 기다려주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Loading_Text {
            get {
                return ResourceManager.GetString("Loading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Baudrate {
            get {
                return ResourceManager.GetString("Title_Baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시리얼포트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Comport {
            get {
                return ResourceManager.GetString("Title_Comport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Help {
            get {
                return ResourceManager.GetString("Title_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Language {
            get {
                return ResourceManager.GetString("Title_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시리얼포트에 연결되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NotConnected {
            get {
                return ResourceManager.GetString("Title_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Search {
            get {
                return ResourceManager.GetString("Title_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작 시 장비조회 팝업 유무과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_StartupPopup {
            get {
                return ResourceManager.GetString("Title_StartupPopup", resourceCulture);
            }
        }
    }
}
