//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurirobotSupporter {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NurirobotSupporter.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   대상 목록 상에 모든 장비에 대해 개별로 설정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Broadcast {
            get {
                return ResourceManager.GetString("Alert_Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경이 실패하였습니다.\r변경된 설정이 있는지 확인 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_DoNotChange {
            get {
                return ResourceManager.GetString("Alert_DoNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그래프 사용 중에 조회할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_IsGraphOn {
            get {
                return ResourceManager.GetString("Alert_IsGraphOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신속도를 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_No_BaudRate {
            get {
                return ResourceManager.GetString("Alert_No_BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대상 장비를 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_NotFound {
            get {
                return ResourceManager.GetString("Alert_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신 중에 문제가 발생하였습니다.\r잠시 후 다시 시도 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Refresh {
            get {
                return ResourceManager.GetString("Alert_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시리얼포트에 이미 연결되어 있습니다. 연결을 해제하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Serial_Connected {
            get {
                return ResourceManager.GetString("Alert_Serial_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 기능은 일괄 적용할 수 없습니다.\r[전체 적용] 체크를 해제하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Setting_Broadcast {
            get {
                return ResourceManager.GetString("Alert_Setting_Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경할 수 없습니다.\r변경하려는 ID가 이미 있거나, 변경할 ID가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Setting_ExistID {
            get {
                return ResourceManager.GetString("Alert_Setting_ExistID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용이 불가능한 장비입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Setting_NotFoundProtocol {
            get {
                return ResourceManager.GetString("Alert_Setting_NotFoundProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경하려는 ID와 현재의 ID가 동일합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Setting_SameID {
            get {
                return ResourceManager.GetString("Alert_Setting_SameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   체크섬과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_ChecksumCalc {
            get {
                return ResourceManager.GetString("Button_ChecksumCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매크로 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_DeviceSearch {
            get {
                return ResourceManager.GetString("Button_DeviceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결해제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Disconnect {
            get {
                return ResourceManager.GetString("Button_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   편집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_English {
            get {
                return ResourceManager.GetString("Button_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매크로 내보내기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매크로 가져오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Import {
            get {
                return ResourceManager.GetString("Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한국어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Korean {
            get {
                return ResourceManager.GetString("Button_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Logclear {
            get {
                return ResourceManager.GetString("Button_Logclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매크로 삽입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_MacroCall {
            get {
                return ResourceManager.GetString("Button_MacroCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로 만들기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반영과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치 리셋과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_PosReset {
            get {
                return ResourceManager.GetString("Button_PosReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전문복사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Protocol {
            get {
                return ResourceManager.GetString("Button_Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제거과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Run {
            get {
                return ResourceManager.GetString("Button_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Search_Start {
            get {
                return ResourceManager.GetString("Button_Search_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Search_Stop {
            get {
                return ResourceManager.GetString("Button_Search_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Set {
            get {
                return ResourceManager.GetString("Button_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지연시간 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Sleep {
            get {
                return ResourceManager.GetString("Button_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Test {
            get {
                return ResourceManager.GetString("Button_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가감속 위치 제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_ControlAcceleratedPos {
            get {
                return ResourceManager.GetString("Desc_ControlAcceleratedPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가감속 속도 제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_ControlAcceleratedSpeed {
            get {
                return ResourceManager.GetString("Desc_ControlAcceleratedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치, 속도제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_ControlPosSpeed {
            get {
                return ResourceManager.GetString("Desc_ControlPosSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모터 컨트롤러 제어 객체과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_NuriMC {
            get {
                return ResourceManager.GetString("Desc_NuriMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스마트액츄에이터 제어 객체과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_NuriRSA {
            get {
                return ResourceManager.GetString("Desc_NuriRSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스마트액츄에이터(뷰웍스) 제어 객체과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_NuriRSAVW {
            get {
                return ResourceManager.GetString("Desc_NuriRSAVW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스마트모터 제어 객체과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_NuriSM {
            get {
                return ResourceManager.GetString("Desc_NuriSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공장 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_ResetFactory {
            get {
                return ResourceManager.GetString("Desc_ResetFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_ResetPostion {
            get {
                return ResourceManager.GetString("Desc_ResetPostion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신속도 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_SettingBaudrate {
            get {
                return ResourceManager.GetString("Desc_SettingBaudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제어 방향 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_SettingControlDirection {
            get {
                return ResourceManager.GetString("Desc_SettingControlDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제어 On/Off 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_SettingControlOnOff {
            get {
                return ResourceManager.GetString("Desc_SettingControlOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_SettingID {
            get {
                return ResourceManager.GetString("Desc_SettingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치제어 모드 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_SettingPositionControl {
            get {
                return ResourceManager.GetString("Desc_SettingPositionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치제어기 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_SettingPositionController {
            get {
                return ResourceManager.GetString("Desc_SettingPositionController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모터 정격속도 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_SettingRatedspeed {
            get {
                return ResourceManager.GetString("Desc_SettingRatedspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   감속비 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_SettingRatio {
            get {
                return ResourceManager.GetString("Desc_SettingRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분해능 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_SettingResolution {
            get {
                return ResourceManager.GetString("Desc_SettingResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신 응답시간 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_SettingResponsetime {
            get {
                return ResourceManager.GetString("Desc_SettingResponsetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   속도제어기 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_SettingSpeedController {
            get {
                return ResourceManager.GetString("Desc_SettingSpeedController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지연시간 설정 함수 예) 1초 대기 :Thread.Sleep(1000);과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc_ThreadSleep {
            get {
                return ResourceManager.GetString("Desc_ThreadSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   절대 위치제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Absolute {
            get {
                return ResourceManager.GetString("Label_Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도달시간(초)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Arrival {
            get {
                return ResourceManager.GetString("Label_Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신속도 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Baudrate {
            get {
                return ResourceManager.GetString("Label_Baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Broadcast {
            get {
                return ResourceManager.GetString("Label_Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경할 아이디과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_ChangeID {
            get {
                return ResourceManager.GetString("Label_ChangeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Choose {
            get {
                return ResourceManager.GetString("Label_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제어 On/Off 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_ControlOnOff {
            get {
                return ResourceManager.GetString("Label_ControlOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정격전류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Current {
            get {
                return ResourceManager.GetString("Label_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지연시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Delay {
            get {
                return ResourceManager.GetString("Label_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 연결 정보을 찾습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_DeviceSearchDesc {
            get {
                return ResourceManager.GetString("Label_DeviceSearchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반시계방향과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_DirectCCW {
            get {
                return ResourceManager.GetString("Label_DirectCCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시계방향과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_DirectCW {
            get {
                return ResourceManager.GetString("Label_DirectCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제어 방향 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Direction {
            get {
                return ResourceManager.GetString("Label_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에코 모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_EchoMode {
            get {
                return ResourceManager.GetString("Label_EchoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분해능 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_EncorderPulsePole {
            get {
                return ResourceManager.GetString("Label_EncorderPulsePole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공장 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_FactoryReset {
            get {
                return ResourceManager.GetString("Label_FactoryReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_ID {
            get {
                return ResourceManager.GetString("Label_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집주기(초)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Intervalsecond {
            get {
                return ResourceManager.GetString("Label_Intervalsecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_IsOk {
            get {
                return ResourceManager.GetString("Label_IsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_LogOff {
            get {
                return ResourceManager.GetString("Label_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_LogOn {
            get {
                return ResourceManager.GetString("Label_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그뷰어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Logview {
            get {
                return ResourceManager.GetString("Label_Logview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반복여부과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Loop {
            get {
                return ResourceManager.GetString("Label_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매크로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Macro {
            get {
                return ResourceManager.GetString("Label_Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   끄기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Off {
            get {
                return ResourceManager.GetString("Label_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   켜기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_On {
            get {
                return ResourceManager.GetString("Label_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_PopupTitleDeviceSearch {
            get {
                return ResourceManager.GetString("Label_PopupTitleDeviceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_POS {
            get {
                return ResourceManager.GetString("Label_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치제어기 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_PosGain {
            get {
                return ResourceManager.GetString("Label_PosGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Position {
            get {
                return ResourceManager.GetString("Label_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_PostionReset {
            get {
                return ResourceManager.GetString("Label_PostionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치제어 모드 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_PostrionCtrl {
            get {
                return ResourceManager.GetString("Label_PostrionCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치, 속도제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_POSVEL {
            get {
                return ResourceManager.GetString("Label_POSVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   처리 중단과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_ProcessStop {
            get {
                return ResourceManager.GetString("Label_ProcessStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전문과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Protocol {
            get {
                return ResourceManager.GetString("Label_Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모터 정격속도 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_RatedSpeed {
            get {
                return ResourceManager.GetString("Label_RatedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   감속비 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Ratio {
            get {
                return ResourceManager.GetString("Label_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   감속비과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Ratio_Title {
            get {
                return ResourceManager.GetString("Label_Ratio_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상대 위치제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Relative {
            get {
                return ResourceManager.GetString("Label_Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분해능과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Resolution {
            get {
                return ResourceManager.GetString("Label_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신 응답시간 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Responsetime {
            get {
                return ResourceManager.GetString("Label_Responsetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RPM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_RPM {
            get {
                return ResourceManager.GetString("Label_RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   단축키과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Shortcut {
            get {
                return ResourceManager.GetString("Label_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   끄기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_StartupPopupOff {
            get {
                return ResourceManager.GetString("Label_StartupPopupOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   켜기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_StartupPopupOn {
            get {
                return ResourceManager.GetString("Label_StartupPopupOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대상 장비과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Targetdevice {
            get {
                return ResourceManager.GetString("Label_Targetdevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제목과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_UnitBaudrate {
            get {
                return ResourceManager.GetString("Label_UnitBaudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   응답시간(us)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_usTime {
            get {
                return ResourceManager.GetString("Label_usTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   속도제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_VEL {
            get {
                return ResourceManager.GetString("Label_VEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Velocity {
            get {
                return ResourceManager.GetString("Label_Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   속도제어기 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_VelocityGain {
            get {
                return ResourceManager.GetString("Label_VelocityGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_English {
            get {
                return ResourceManager.GetString("Left_Menu_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Help {
            get {
                return ResourceManager.GetString("Left_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Language {
            get {
                return ResourceManager.GetString("Left_Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매크로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Macro {
            get {
                return ResourceManager.GetString("Left_Menu_Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다중 제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Multiple_Control {
            get {
                return ResourceManager.GetString("Left_Menu_Multiple_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Search {
            get {
                return ResourceManager.GetString("Left_Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Setting {
            get {
                return ResourceManager.GetString("Left_Menu_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   단독 제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Single_Control {
            get {
                return ResourceManager.GetString("Left_Menu_Single_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   터미날과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Terminal {
            get {
                return ResourceManager.GetString("Left_Menu_Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메뉴과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Title {
            get {
                return ResourceManager.GetString("Left_Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   처리중입니다. 기다려주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Loading_Text {
            get {
                return ResourceManager.GetString("Loading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내보내기를 성공하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Popup_ExportDone {
            get {
                return ResourceManager.GetString("Popup_ExportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가져오기를 성공하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Popup_ImportDone {
            get {
                return ResourceManager.GetString("Popup_ImportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   처리 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PopupDone {
            get {
                return ResourceManager.GetString("PopupDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Baudrate {
            get {
                return ResourceManager.GetString("Title_Baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시리얼포트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Comport {
            get {
                return ResourceManager.GetString("Title_Comport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매크로 편집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_EditMacro {
            get {
                return ResourceManager.GetString("Title_EditMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   피드백과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Feedback {
            get {
                return ResourceManager.GetString("Title_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그래프 표시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Graph {
            get {
                return ResourceManager.GetString("Title_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Help {
            get {
                return ResourceManager.GetString("Title_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정 적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_IsOk {
            get {
                return ResourceManager.GetString("Title_IsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Language {
            get {
                return ResourceManager.GetString("Title_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매크로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Macro {
            get {
                return ResourceManager.GetString("Title_Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다중 제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Multiple {
            get {
                return ResourceManager.GetString("Title_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시리얼포트에 연결되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_NotConnected {
            get {
                return ResourceManager.GetString("Title_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Search {
            get {
                return ResourceManager.GetString("Title_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Setting {
            get {
                return ResourceManager.GetString("Title_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에러로그 표시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_ShowError {
            get {
                return ResourceManager.GetString("Title_ShowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   단독 제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Single {
            get {
                return ResourceManager.GetString("Title_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작 시 장비조회 팝업 유무과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_StartupPopup {
            get {
                return ResourceManager.GetString("Title_StartupPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시리얼 터미날과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Terminal {
            get {
                return ResourceManager.GetString("Title_Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제어기능과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Tool {
            get {
                return ResourceManager.GetString("Title_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   헥사 데이터를 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Tooltip_HexInput {
            get {
                return ResourceManager.GetString("Tooltip_HexInput", resourceCulture);
            }
        }
    }
}
