//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurirobotSupporter {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NurirobotSupporter.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   대상 목록 상에 모든 장비에 대해 개별로 설정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Broadcast {
            get {
                return ResourceManager.GetString("Alert_Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경이 실패하였습니다.\r변경된 설정이 있는지 확인 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_DoNotChange {
            get {
                return ResourceManager.GetString("Alert_DoNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신속도를 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_No_BaudRate {
            get {
                return ResourceManager.GetString("Alert_No_BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대상 장비를 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_NotFound {
            get {
                return ResourceManager.GetString("Alert_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시리얼포트에 이미 연결되어 있습니다. 연결을 해제하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Serial_Connected {
            get {
                return ResourceManager.GetString("Alert_Serial_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 기능은 일괄 적용할 수 없습니다.\r[전체 적용] 체크를 해제하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Setting_Broadcast {
            get {
                return ResourceManager.GetString("Alert_Setting_Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경할 수 없습니다.\r변경하려는 ID가 이미 있거나, 변경할 ID가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Setting_ExistID {
            get {
                return ResourceManager.GetString("Alert_Setting_ExistID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용이 불가능한 장비입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Setting_NotFoundProtocol {
            get {
                return ResourceManager.GetString("Alert_Setting_NotFoundProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경하려는 ID와 현재의 ID가 동일합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alert_Setting_SameID {
            get {
                return ResourceManager.GetString("Alert_Setting_SameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_DeviceSearch {
            get {
                return ResourceManager.GetString("Button_DeviceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결해제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Disconnect {
            get {
                return ResourceManager.GetString("Button_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_English {
            get {
                return ResourceManager.GetString("Button_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한국어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Korean {
            get {
                return ResourceManager.GetString("Button_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Search_Start {
            get {
                return ResourceManager.GetString("Button_Search_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Search_Stop {
            get {
                return ResourceManager.GetString("Button_Search_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Button_Set {
            get {
                return ResourceManager.GetString("Button_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   절대 위치제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Absolute {
            get {
                return ResourceManager.GetString("Label_Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신속도 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Baudrate {
            get {
                return ResourceManager.GetString("Label_Baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Broadcast {
            get {
                return ResourceManager.GetString("Label_Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경할 아이디과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_ChangeID {
            get {
                return ResourceManager.GetString("Label_ChangeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제어 On/Off 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_ControlOnOff {
            get {
                return ResourceManager.GetString("Label_ControlOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정격전류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Current {
            get {
                return ResourceManager.GetString("Label_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 연결 정보을 찾습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_DeviceSearchDesc {
            get {
                return ResourceManager.GetString("Label_DeviceSearchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반시계방향과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_DirectCCW {
            get {
                return ResourceManager.GetString("Label_DirectCCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시계방향과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_DirectCW {
            get {
                return ResourceManager.GetString("Label_DirectCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제어 방향 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Direction {
            get {
                return ResourceManager.GetString("Label_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분해능 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_EncorderPulsePole {
            get {
                return ResourceManager.GetString("Label_EncorderPulsePole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공장 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_FactoryReset {
            get {
                return ResourceManager.GetString("Label_FactoryReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_ID {
            get {
                return ResourceManager.GetString("Label_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_IsOk {
            get {
                return ResourceManager.GetString("Label_IsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_LogOff {
            get {
                return ResourceManager.GetString("Label_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_LogOn {
            get {
                return ResourceManager.GetString("Label_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그뷰어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Logview {
            get {
                return ResourceManager.GetString("Label_Logview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   끄기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Off {
            get {
                return ResourceManager.GetString("Label_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   켜기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_On {
            get {
                return ResourceManager.GetString("Label_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_PopupTitleDeviceSearch {
            get {
                return ResourceManager.GetString("Label_PopupTitleDeviceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치제어기 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_PosGain {
            get {
                return ResourceManager.GetString("Label_PosGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_PostionReset {
            get {
                return ResourceManager.GetString("Label_PostionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치제어 모드 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_PostrionCtrl {
            get {
                return ResourceManager.GetString("Label_PostrionCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모터 정격속도 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_RatedSpeed {
            get {
                return ResourceManager.GetString("Label_RatedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   감속비 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Ratio {
            get {
                return ResourceManager.GetString("Label_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   감속비과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Ratio_Title {
            get {
                return ResourceManager.GetString("Label_Ratio_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상대 위치제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Relative {
            get {
                return ResourceManager.GetString("Label_Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분해능과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Resolution {
            get {
                return ResourceManager.GetString("Label_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신 응답시간 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Responsetime {
            get {
                return ResourceManager.GetString("Label_Responsetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RPM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_RPM {
            get {
                return ResourceManager.GetString("Label_RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   끄기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_StartupPopupOff {
            get {
                return ResourceManager.GetString("Label_StartupPopupOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   켜기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_StartupPopupOn {
            get {
                return ResourceManager.GetString("Label_StartupPopupOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대상 장비과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_Targetdevice {
            get {
                return ResourceManager.GetString("Label_Targetdevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_UnitBaudrate {
            get {
                return ResourceManager.GetString("Label_UnitBaudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   응답시간(us)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_usTime {
            get {
                return ResourceManager.GetString("Label_usTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   속도제어기 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Label_VelocityGain {
            get {
                return ResourceManager.GetString("Label_VelocityGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_English {
            get {
                return ResourceManager.GetString("Left_Menu_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Help {
            get {
                return ResourceManager.GetString("Left_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Language {
            get {
                return ResourceManager.GetString("Left_Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매크로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Macro {
            get {
                return ResourceManager.GetString("Left_Menu_Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다중 제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Multiple_Control {
            get {
                return ResourceManager.GetString("Left_Menu_Multiple_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Search {
            get {
                return ResourceManager.GetString("Left_Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Setting {
            get {
                return ResourceManager.GetString("Left_Menu_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   단독 제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Single_Control {
            get {
                return ResourceManager.GetString("Left_Menu_Single_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메뉴과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left_Menu_Title {
            get {
                return ResourceManager.GetString("Left_Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   처리중입니다. 기다려주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Loading_Text {
            get {
                return ResourceManager.GetString("Loading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   처리 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PopupDone {
            get {
                return ResourceManager.GetString("PopupDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Baudrate {
            get {
                return ResourceManager.GetString("Title_Baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시리얼포트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Comport {
            get {
                return ResourceManager.GetString("Title_Comport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Help {
            get {
                return ResourceManager.GetString("Title_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정 적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_IsOk {
            get {
                return ResourceManager.GetString("Title_IsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Language {
            get {
                return ResourceManager.GetString("Title_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시리얼포트에 연결되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_NotConnected {
            get {
                return ResourceManager.GetString("Title_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Search {
            get {
                return ResourceManager.GetString("Title_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작 시 장비조회 팝업 유무과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_StartupPopup {
            get {
                return ResourceManager.GetString("Title_StartupPopup", resourceCulture);
            }
        }
    }
}
